package com.jzh.news.entity;

public class tb_domain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_domain.DomainID
     *
     * @mbg.generated
     */
    private String domainid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_domain.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_domain.IsDelete
     *
     * @mbg.generated
     */
    private String isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_domain.Represent
     *
     * @mbg.generated
     */
    private String represent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_domain.DomainID
     *
     * @return the value of tb_domain.DomainID
     *
     * @mbg.generated
     */
    public String getDomainid() {
        return domainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_domain.DomainID
     *
     * @param domainid the value for tb_domain.DomainID
     *
     * @mbg.generated
     */
    public void setDomainid(String domainid) {
        this.domainid = domainid == null ? null : domainid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_domain.Name
     *
     * @return the value of tb_domain.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_domain.Name
     *
     * @param name the value for tb_domain.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_domain.IsDelete
     *
     * @return the value of tb_domain.IsDelete
     *
     * @mbg.generated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_domain.IsDelete
     *
     * @param isdelete the value for tb_domain.IsDelete
     *
     * @mbg.generated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_domain.Represent
     *
     * @return the value of tb_domain.Represent
     *
     * @mbg.generated
     */
    public String getRepresent() {
        return represent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_domain.Represent
     *
     * @param represent the value for tb_domain.Represent
     *
     * @mbg.generated
     */
    public void setRepresent(String represent) {
        this.represent = represent == null ? null : represent.trim();
    }
}