package com.yyquan.zkzx.entity;

import java.io.Serializable;
import java.util.Date;

public class tb_topicforumprocess implements Serializable {
    private static final long serialVersionUID = 4257164909610823151L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.UserID
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.UserName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.ThemeID
     *
     * @mbg.generated
     */
    private String themeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.DiscussContent
     *
     * @mbg.generated
     */
    private String discusscontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.DiscussContentType
     *
     * @mbg.generated
     * 1.主要观点；2.重点问题；3.指标数据；4.结论
     */
    private String discusscontenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.PraiseCount
     *
     * @mbg.generated
     */
    private Integer praisecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.ReferenceID
     *
     * @mbg.generated
     */
    private Integer referenceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.ReferenceCount
     *
     * @mbg.generated
     */
    private Integer referencecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.DiscussTime
     *
     * @mbg.generated
     */
    private Date discusstime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.ID
     *
     * @return the value of tb_topicforumprocess.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.ID
     *
     * @param id the value for tb_topicforumprocess.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.UserID
     *
     * @return the value of tb_topicforumprocess.UserID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.UserID
     *
     * @param userid the value for tb_topicforumprocess.UserID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.UserName
     *
     * @return the value of tb_topicforumprocess.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.UserName
     *
     * @param username the value for tb_topicforumprocess.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.ThemeID
     *
     * @return the value of tb_topicforumprocess.ThemeID
     *
     * @mbg.generated
     */
    public String getThemeid() {
        return themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.ThemeID
     *
     * @param themeid the value for tb_topicforumprocess.ThemeID
     *
     * @mbg.generated
     */
    public void setThemeid(String themeid) {
        this.themeid = themeid == null ? null : themeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.DiscussContent
     *
     * @return the value of tb_topicforumprocess.DiscussContent
     *
     * @mbg.generated
     */
    public String getDiscusscontent() {
        return discusscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.DiscussContent
     *
     * @param discusscontent the value for tb_topicforumprocess.DiscussContent
     *
     * @mbg.generated
     */
    public void setDiscusscontent(String discusscontent) {
        this.discusscontent = discusscontent == null ? null : discusscontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.DiscussContentType
     *
     * @return the value of tb_topicforumprocess.DiscussContentType
     *
     * @mbg.generated
     */
    public String getDiscusscontenttype() {
        return discusscontenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.DiscussContentType
     *
     * @param discusscontenttype the value for tb_topicforumprocess.DiscussContentType
     *
     * @mbg.generated
     */
    public void setDiscusscontenttype(String discusscontenttype) {
        this.discusscontenttype = discusscontenttype == null ? null : discusscontenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.PraiseCount
     *
     * @return the value of tb_topicforumprocess.PraiseCount
     *
     * @mbg.generated
     */
    public Integer getPraisecount() {
        return praisecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.PraiseCount
     *
     * @param praisecount the value for tb_topicforumprocess.PraiseCount
     *
     * @mbg.generated
     */
    public void setPraisecount(Integer praisecount) {
        this.praisecount = praisecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.ReferenceID
     *
     * @return the value of tb_topicforumprocess.ReferenceID
     *
     * @mbg.generated
     */
    public Integer getReferenceid() {
        return referenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.ReferenceID
     *
     * @param referenceid the value for tb_topicforumprocess.ReferenceID
     *
     * @mbg.generated
     */
    public void setReferenceid(Integer referenceid) {
        this.referenceid = referenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.ReferenceCount
     *
     * @return the value of tb_topicforumprocess.ReferenceCount
     *
     * @mbg.generated
     */
    public Integer getReferencecount() {
        return referencecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.ReferenceCount
     *
     * @param referencecount the value for tb_topicforumprocess.ReferenceCount
     *
     * @mbg.generated
     */
    public void setReferencecount(Integer referencecount) {
        this.referencecount = referencecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.DiscussTime
     *
     * @return the value of tb_topicforumprocess.DiscussTime
     *
     * @mbg.generated
     */
    public Date getDiscusstime() {
        return discusstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.DiscussTime
     *
     * @param discusstime the value for tb_topicforumprocess.DiscussTime
     *
     * @mbg.generated
     */
    public void setDiscusstime(Date discusstime) {
        this.discusstime = discusstime;
    }
}