package com.yyquan.zkzx.entity;

import java.util.Date;

public class tb_user {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.UserID
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.QQ
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.City
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Years
     *
     * @mbg.generated
     */
    private String years;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Qianming
     *
     * @mbg.generated
     */
    private String qianming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.CreateID
     *
     * @mbg.generated
     */
    private String createid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.UpdateID
     *
     * @mbg.generated
     */
    private String updateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.UpdateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.MailBox
     *
     * @mbg.generated
     */
    private String mailbox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ContactInformation
     *
     * @mbg.generated
     */
    private String contactinformation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.BriefIntroduction
     *
     * @mbg.generated
     */
    private String briefintroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.HeadImagePath
     *
     * @mbg.generated
     */
    private String headimagepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Job
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.DomainID
     *
     * @mbg.generated
     */
    private String domainid;

    private String domainarea;

    public String getDomainarea() {
        return domainarea;
    }

    public void setDomainarea(String domainarea) {
        this.domainarea = domainarea;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Age
     *
     * @mbg.generated
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.UserOrExpert
     *
     * @mbg.generated
     */
    private String userorexpert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.IsDelete
     *
     * @mbg.generated
     */
    private String isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.DepartmentID
     *
     * @mbg.generated
     */
    private String departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.GradeID
     *
     * @mbg.generated
     */
    private String gradeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.UserID
     *
     * @return the value of tb_user.UserID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.UserID
     *
     * @param userid the value for tb_user.UserID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Account
     *
     * @return the value of tb_user.Account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Account
     *
     * @param account the value for tb_user.Account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Password
     *
     * @return the value of tb_user.Password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Password
     *
     * @param password the value for tb_user.Password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Name
     *
     * @return the value of tb_user.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Name
     *
     * @param name the value for tb_user.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.QQ
     *
     * @return the value of tb_user.QQ
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.QQ
     *
     * @param qq the value for tb_user.QQ
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.City
     *
     * @return the value of tb_user.City
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.City
     *
     * @param city the value for tb_user.City
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Location
     *
     * @return the value of tb_user.Location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Location
     *
     * @param location the value for tb_user.Location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Years
     *
     * @return the value of tb_user.Years
     *
     * @mbg.generated
     */
    public String getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Years
     *
     * @param years the value for tb_user.Years
     *
     * @mbg.generated
     */
    public void setYears(String years) {
        this.years = years == null ? null : years.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Qianming
     *
     * @return the value of tb_user.Qianming
     *
     * @mbg.generated
     */
    public String getQianming() {
        return qianming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Qianming
     *
     * @param qianming the value for tb_user.Qianming
     *
     * @mbg.generated
     */
    public void setQianming(String qianming) {
        this.qianming = qianming == null ? null : qianming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.CreateID
     *
     * @return the value of tb_user.CreateID
     *
     * @mbg.generated
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.CreateID
     *
     * @param createid the value for tb_user.CreateID
     *
     * @mbg.generated
     */
    public void setCreateid(String createid) {
        this.createid = createid == null ? null : createid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.CreateTime
     *
     * @return the value of tb_user.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.CreateTime
     *
     * @param createtime the value for tb_user.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.UpdateID
     *
     * @return the value of tb_user.UpdateID
     *
     * @mbg.generated
     */
    public String getUpdateid() {
        return updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.UpdateID
     *
     * @param updateid the value for tb_user.UpdateID
     *
     * @mbg.generated
     */
    public void setUpdateid(String updateid) {
        this.updateid = updateid == null ? null : updateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.UpdateTime
     *
     * @return the value of tb_user.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.UpdateTime
     *
     * @param updatetime the value for tb_user.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Sex
     *
     * @return the value of tb_user.Sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Sex
     *
     * @param sex the value for tb_user.Sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Birthday
     *
     * @return the value of tb_user.Birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Birthday
     *
     * @param birthday the value for tb_user.Birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MailBox
     *
     * @return the value of tb_user.MailBox
     *
     * @mbg.generated
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MailBox
     *
     * @param mailbox the value for tb_user.MailBox
     *
     * @mbg.generated
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox == null ? null : mailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ContactInformation
     *
     * @return the value of tb_user.ContactInformation
     *
     * @mbg.generated
     */
    public String getContactinformation() {
        return contactinformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ContactInformation
     *
     * @param contactinformation the value for tb_user.ContactInformation
     *
     * @mbg.generated
     */
    public void setContactinformation(String contactinformation) {
        this.contactinformation = contactinformation == null ? null : contactinformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.BriefIntroduction
     *
     * @return the value of tb_user.BriefIntroduction
     *
     * @mbg.generated
     */
    public String getBriefintroduction() {
        return briefintroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.BriefIntroduction
     *
     * @param briefintroduction the value for tb_user.BriefIntroduction
     *
     * @mbg.generated
     */
    public void setBriefintroduction(String briefintroduction) {
        this.briefintroduction = briefintroduction == null ? null : briefintroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.HeadImagePath
     *
     * @return the value of tb_user.HeadImagePath
     *
     * @mbg.generated
     */
    public String getHeadimagepath() {
        return headimagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.HeadImagePath
     *
     * @param headimagepath the value for tb_user.HeadImagePath
     *
     * @mbg.generated
     */
    public void setHeadimagepath(String headimagepath) {
        this.headimagepath = headimagepath == null ? null : headimagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Job
     *
     * @return the value of tb_user.Job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Job
     *
     * @param job the value for tb_user.Job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.DomainID
     *
     * @return the value of tb_user.DomainID
     *
     * @mbg.generated
     */
    public String getDomainid() {
        return domainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.DomainID
     *
     * @param domainid the value for tb_user.DomainID
     *
     * @mbg.generated
     */
    public void setDomainid(String domainid) {
        this.domainid = domainid == null ? null : domainid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Age
     *
     * @return the value of tb_user.Age
     *
     * @mbg.generated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Age
     *
     * @param age the value for tb_user.Age
     *
     * @mbg.generated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Company
     *
     * @return the value of tb_user.Company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Company
     *
     * @param company the value for tb_user.Company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.UserOrExpert
     *
     * @return the value of tb_user.UserOrExpert
     *
     * @mbg.generated
     */
    public String getUserorexpert() {
        return userorexpert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.UserOrExpert
     *
     * @param userorexpert the value for tb_user.UserOrExpert
     *
     * @mbg.generated
     */
    public void setUserorexpert(String userorexpert) {
        this.userorexpert = userorexpert == null ? null : userorexpert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IsDelete
     *
     * @return the value of tb_user.IsDelete
     *
     * @mbg.generated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IsDelete
     *
     * @param isdelete the value for tb_user.IsDelete
     *
     * @mbg.generated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.DepartmentID
     *
     * @return the value of tb_user.DepartmentID
     *
     * @mbg.generated
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.DepartmentID
     *
     * @param departmentid the value for tb_user.DepartmentID
     *
     * @mbg.generated
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.GradeID
     *
     * @return the value of tb_user.GradeID
     *
     * @mbg.generated
     */
    public String getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.GradeID
     *
     * @param gradeid the value for tb_user.GradeID
     *
     * @mbg.generated
     */
    public void setGradeid(String gradeid) {
        this.gradeid = gradeid == null ? null : gradeid.trim();
    }
}