package com.jzh.news.entity;

import javax.persistence.Column;
import javax.persistence.Entity;

@Entity
public class tb_discussiongroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_discussiongroup.ID
     *
     * @mbg.generated
     */
	@Column(name="id")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_discussiongroup.TaskID
     *
     * @mbg.generated
     */
	@Column(name="taskid")
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_discussiongroup.RoleID
     *
     * @mbg.generated
     */
	@Column(name="roleid")
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_discussiongroup.ExpertTopicScore
     *
     * @mbg.generated
     */
	@Column(name="experttopicscore")
    private Integer experttopicscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_discussiongroup.UserID
     *
     * @mbg.generated
     */
	@Column(name="userid")
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_discussiongroup.ID
     *
     * @return the value of tb_discussiongroup.ID
     *
     * @mbg.generated
     */ 
	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_discussiongroup.ID
     *
     * @param id the value for tb_discussiongroup.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_discussiongroup.TaskID
     *
     * @return the value of tb_discussiongroup.TaskID
     *
     * @mbg.generated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_discussiongroup.TaskID
     *
     * @param taskid the value for tb_discussiongroup.TaskID
     *
     * @mbg.generated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_discussiongroup.RoleID
     *
     * @return the value of tb_discussiongroup.RoleID
     *
     * @mbg.generated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_discussiongroup.RoleID
     *
     * @param roleid the value for tb_discussiongroup.RoleID
     *
     * @mbg.generated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_discussiongroup.ExpertTopicScore
     *
     * @return the value of tb_discussiongroup.ExpertTopicScore
     *
     * @mbg.generated
     */
    public Integer getExperttopicscore() {
        return experttopicscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_discussiongroup.ExpertTopicScore
     *
     * @param experttopicscore the value for tb_discussiongroup.ExpertTopicScore
     *
     * @mbg.generated
     */
    public void setExperttopicscore(Integer experttopicscore) {
        this.experttopicscore = experttopicscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_discussiongroup.UserID
     *
     * @return the value of tb_discussiongroup.UserID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_discussiongroup.UserID
     *
     * @param userid the value for tb_discussiongroup.UserID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}