package com.jzh.news.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
@Entity
public class tb_role implements Serializable {
	
    /**
	 * 
	 */
	private static final long serialVersionUID = -5877655305230612353L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.RoleId
     *
     * @mbg.generated
     */
	@Column(name="roleid")
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.RoleName
     *
     * @mbg.generated
     */
	@Column(name="rolename")
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.CreatID
     *
     * @mbg.generated
     */
	@Column(name="creatid")
    private String creatid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.CreatTime
     *
     * @mbg.generated
     */
	@Column(name="creattime")
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.UpdateID
     *
     * @mbg.generated
     */
	@Column(name="updateid")
    private String updateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.UpdateTime
     *
     * @mbg.generated
     */
	@Column(name="updatetime")
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.IsDelete
     *
     * @mbg.generated
     */
	@Column(name="isdelete")
    private String isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.Represent
     *
     * @mbg.generated
     */
	@Column(name="represent")
    private String represent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.RoleId
     *
     * @return the value of tb_role.RoleId
     *
     * @mbg.generated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.RoleId
     *
     * @param roleid the value for tb_role.RoleId
     *
     * @mbg.generated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.RoleName
     *
     * @return the value of tb_role.RoleName
     *
     * @mbg.generated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.RoleName
     *
     * @param rolename the value for tb_role.RoleName
     *
     * @mbg.generated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.CreatID
     *
     * @return the value of tb_role.CreatID
     *
     * @mbg.generated
     */
    public String getCreatid() {
        return creatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.CreatID
     *
     * @param creatid the value for tb_role.CreatID
     *
     * @mbg.generated
     */
    public void setCreatid(String creatid) {
        this.creatid = creatid == null ? null : creatid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.CreatTime
     *
     * @return the value of tb_role.CreatTime
     *
     * @mbg.generated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.CreatTime
     *
     * @param creattime the value for tb_role.CreatTime
     *
     * @mbg.generated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.UpdateID
     *
     * @return the value of tb_role.UpdateID
     *
     * @mbg.generated
     */
    public String getUpdateid() {
        return updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.UpdateID
     *
     * @param updateid the value for tb_role.UpdateID
     *
     * @mbg.generated
     */
    public void setUpdateid(String updateid) {
        this.updateid = updateid == null ? null : updateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.UpdateTime
     *
     * @return the value of tb_role.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.UpdateTime
     *
     * @param updatetime the value for tb_role.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.IsDelete
     *
     * @return the value of tb_role.IsDelete
     *
     * @mbg.generated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.IsDelete
     *
     * @param isdelete the value for tb_role.IsDelete
     *
     * @mbg.generated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.Represent
     *
     * @return the value of tb_role.Represent
     *
     * @mbg.generated
     */
    public String getRepresent() {
        return represent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.Represent
     *
     * @param represent the value for tb_role.Represent
     *
     * @mbg.generated
     */
    public void setRepresent(String represent) {
        this.represent = represent == null ? null : represent.trim();
    }
}