package com.jzh.news.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
@Entity
public class tb_scheduleplannerpro {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.TaskID
     *
     * @mbg.generated
     */
	@Column(name="taskid")
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.TaskName
     *
     * @mbg.generated
     */
	@Column(name="taskname")
    private String taskname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.ProblemID
     *
     * @mbg.generated
     */
    @Column(name="problemid")
    private String problemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.SubjectID
     *
     * @mbg.generated
     */
    @Column(name="subjectid")
    private String subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.StartStopTime
     *
     * @mbg.generated
     */
    @Column(name="startstoptime")
    private Date startstoptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.IsDelete
     *
     * @mbg.generated
     */
    @Column(name="isdelete")
    private String isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.DiscussionType
     *
     * @mbg.generated
     */
    @Column(name="discussiontype")
    private String discussiontype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.CreateID
     *
     * @mbg.generated
     */
    @Column(name="createid")
    private String createid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.CreateTime
     *
     * @mbg.generated
     */
    @Column(name="createtime")
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.UpdateID
     *
     * @mbg.generated
     */
    @Column(name="updateid")
    private String updateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.UpdateTime
     *
     * @mbg.generated
     */
    @Column(name="updatetime")
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.State
     *
     * @mbg.generated
     */
    @Column(name="state")
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_scheduleplannerpro.Remarks
     *
     * @mbg.generated
     */
    @Column(name="remarks")
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.TaskID
     *
     * @return the value of tb_scheduleplannerpro.TaskID
     *
     * @mbg.generated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.TaskID
     *
     * @param taskid the value for tb_scheduleplannerpro.TaskID
     *
     * @mbg.generated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.TaskName
     *
     * @return the value of tb_scheduleplannerpro.TaskName
     *
     * @mbg.generated
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.TaskName
     *
     * @param taskname the value for tb_scheduleplannerpro.TaskName
     *
     * @mbg.generated
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname == null ? null : taskname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.ProblemID
     *
     * @return the value of tb_scheduleplannerpro.ProblemID
     *
     * @mbg.generated
     */
    public String getProblemid() {
        return problemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.ProblemID
     *
     * @param problemid the value for tb_scheduleplannerpro.ProblemID
     *
     * @mbg.generated
     */
    public void setProblemid(String problemid) {
        this.problemid = problemid == null ? null : problemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.SubjectID
     *
     * @return the value of tb_scheduleplannerpro.SubjectID
     *
     * @mbg.generated
     */
    public String getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.SubjectID
     *
     * @param subjectid the value for tb_scheduleplannerpro.SubjectID
     *
     * @mbg.generated
     */
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid == null ? null : subjectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.StartStopTime
     *
     * @return the value of tb_scheduleplannerpro.StartStopTime
     *
     * @mbg.generated
     */
    public Date getStartstoptime() {
        return startstoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.StartStopTime
     *
     * @param startstoptime the value for tb_scheduleplannerpro.StartStopTime
     *
     * @mbg.generated
     */
    public void setStartstoptime(Date startstoptime) {
        this.startstoptime = startstoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.IsDelete
     *
     * @return the value of tb_scheduleplannerpro.IsDelete
     *
     * @mbg.generated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.IsDelete
     *
     * @param isdelete the value for tb_scheduleplannerpro.IsDelete
     *
     * @mbg.generated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.DiscussionType
     *
     * @return the value of tb_scheduleplannerpro.DiscussionType
     *
     * @mbg.generated
     */
    public String getDiscussiontype() {
        return discussiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.DiscussionType
     *
     * @param discussiontype the value for tb_scheduleplannerpro.DiscussionType
     *
     * @mbg.generated
     */
    public void setDiscussiontype(String discussiontype) {
        this.discussiontype = discussiontype == null ? null : discussiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.CreateID
     *
     * @return the value of tb_scheduleplannerpro.CreateID
     *
     * @mbg.generated
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.CreateID
     *
     * @param createid the value for tb_scheduleplannerpro.CreateID
     *
     * @mbg.generated
     */
    public void setCreateid(String createid) {
        this.createid = createid == null ? null : createid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.CreateTime
     *
     * @return the value of tb_scheduleplannerpro.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.CreateTime
     *
     * @param createtime the value for tb_scheduleplannerpro.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.UpdateID
     *
     * @return the value of tb_scheduleplannerpro.UpdateID
     *
     * @mbg.generated
     */
    public String getUpdateid() {
        return updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.UpdateID
     *
     * @param updateid the value for tb_scheduleplannerpro.UpdateID
     *
     * @mbg.generated
     */
    public void setUpdateid(String updateid) {
        this.updateid = updateid == null ? null : updateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.UpdateTime
     *
     * @return the value of tb_scheduleplannerpro.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.UpdateTime
     *
     * @param updatetime the value for tb_scheduleplannerpro.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.State
     *
     * @return the value of tb_scheduleplannerpro.State
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.State
     *
     * @param state the value for tb_scheduleplannerpro.State
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_scheduleplannerpro.Remarks
     *
     * @return the value of tb_scheduleplannerpro.Remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_scheduleplannerpro.Remarks
     *
     * @param remarks the value for tb_scheduleplannerpro.Remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}