package com.jzh.news.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;

@Entity
public class tb_topicprocessuserpraise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicprocessuserpraise.id
     *
     * @mbg.generated
     */
	@Column(name="id")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicprocessuserpraise.topicprocessid
     *
     * @mbg.generated
     */
	@Column(name="topicprocessid")
    private String topicprocessid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicprocessuserpraise.userid
     *
     * @mbg.generated
     */
	@Column(name="userid")
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicprocessuserpraise.username
     *
     * @mbg.generated
     */
	@Column(name="username")
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicprocessuserpraise.comment
     *
     * @mbg.generated
     */
	@Column(name="comment")
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicprocessuserpraise.isfavorite
     *
     * @mbg.generated
     */
	@Column(name="isfavorite")
    private Boolean  isfavorite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicprocessuserpraise.ispraise
     *
     * @mbg.generated
     */
	@Column(name="ispraise")
    private Boolean  ispraise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicprocessuserpraise.createtime
     *
     * @mbg.generated
     */
	@Column(name="createtime")
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicprocessuserpraise.id
     *
     * @return the value of tb_topicprocessuserpraise.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicprocessuserpraise.id
     *
     * @param id the value for tb_topicprocessuserpraise.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicprocessuserpraise.topicprocessid
     *
     * @return the value of tb_topicprocessuserpraise.topicprocessid
     *
     * @mbg.generated
     */
    public String getTopicprocessid() {
        return topicprocessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicprocessuserpraise.topicprocessid
     *
     * @param topicprocessid the value for tb_topicprocessuserpraise.topicprocessid
     *
     * @mbg.generated
     */
    public void setTopicprocessid(String topicprocessid) {
        this.topicprocessid = topicprocessid == null ? null : topicprocessid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicprocessuserpraise.userid
     *
     * @return the value of tb_topicprocessuserpraise.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicprocessuserpraise.userid
     *
     * @param userid the value for tb_topicprocessuserpraise.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicprocessuserpraise.username
     *
     * @return the value of tb_topicprocessuserpraise.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicprocessuserpraise.username
     *
     * @param username the value for tb_topicprocessuserpraise.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicprocessuserpraise.comment
     *
     * @return the value of tb_topicprocessuserpraise.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicprocessuserpraise.comment
     *
     * @param comment the value for tb_topicprocessuserpraise.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicprocessuserpraise.isfavorite
     *
     * @return the value of tb_topicprocessuserpraise.isfavorite
     *
     * @mbg.generated
     */
    public Boolean getIsfavorite() {
        return isfavorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicprocessuserpraise.isfavorite
     *
     * @param isfavorite the value for tb_topicprocessuserpraise.isfavorite
     *
     * @mbg.generated
     */
    public void setIsfavorite(Boolean isfavorite) {
        this.isfavorite = isfavorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicprocessuserpraise.ispraise
     *
     * @return the value of tb_topicprocessuserpraise.ispraise
     *
     * @mbg.generated
     */
    public Boolean getIspraise() {
        return ispraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicprocessuserpraise.ispraise
     *
     * @param ispraise the value for tb_topicprocessuserpraise.ispraise
     *
     * @mbg.generated
     */
    public void setIspraise(Boolean ispraise) {
        this.ispraise = ispraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicprocessuserpraise.createtime
     *
     * @return the value of tb_topicprocessuserpraise.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicprocessuserpraise.createtime
     *
     * @param createtime the value for tb_topicprocessuserpraise.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}