package com.jzh.news.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;

@Entity
public class tb_topicforumprocess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.ID
     *
     * @mbg.generated
     */
	@Column(name="id")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.UserID
     *
     * @mbg.generated
     */
	@Column(name="userid")
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.UserName
     *
     * @mbg.generated
     */
	@Column(name="username")
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.ThemeID
     *
     * @mbg.generated
     */
	@Column(name="themeid")
    private String themeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.DiscussContent
     *
     * @mbg.generated
     */
	@Column(name="discusscontent")
    private String discusscontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.DiscussContentType
     *
     * @mbg.generated
     */
	@Column(name="discusscontenttype")
    private String discusscontenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.PraiseCount
     *
     * @mbg.generated
     */
	@Column(name="praisecount")
    private Integer praisecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.ReferenceID
     *
     * @mbg.generated
     */
	@Column(name="referenceid")
    private Integer referenceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.ReferenceCount
     *
     * @mbg.generated
     */
	@Column(name="referencecount")
    private Integer referencecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topicforumprocess.DiscussTime
     *
     * @mbg.generated
     */
	@Column(name="discusstime")
    private Date discusstime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.ID
     *
     * @return the value of tb_topicforumprocess.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.ID
     *
     * @param id the value for tb_topicforumprocess.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.UserID
     *
     * @return the value of tb_topicforumprocess.UserID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.UserID
     *
     * @param userid the value for tb_topicforumprocess.UserID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.UserName
     *
     * @return the value of tb_topicforumprocess.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.UserName
     *
     * @param username the value for tb_topicforumprocess.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.ThemeID
     *
     * @return the value of tb_topicforumprocess.ThemeID
     *
     * @mbg.generated
     */
    public String getThemeid() {
        return themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.ThemeID
     *
     * @param themeid the value for tb_topicforumprocess.ThemeID
     *
     * @mbg.generated
     */
    public void setThemeid(String themeid) {
        this.themeid = themeid == null ? null : themeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.DiscussContent
     *
     * @return the value of tb_topicforumprocess.DiscussContent
     *
     * @mbg.generated
     */
    public String getDiscusscontent() {
        return discusscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.DiscussContent
     *
     * @param discusscontent the value for tb_topicforumprocess.DiscussContent
     *
     * @mbg.generated
     */
    public void setDiscusscontent(String discusscontent) {
        this.discusscontent = discusscontent == null ? null : discusscontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.DiscussContentType
     *
     * @return the value of tb_topicforumprocess.DiscussContentType
     *
     * @mbg.generated
     */
    public String getDiscusscontenttype() {
        return discusscontenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.DiscussContentType
     *
     * @param discusscontenttype the value for tb_topicforumprocess.DiscussContentType
     *
     * @mbg.generated
     */
    public void setDiscusscontenttype(String discusscontenttype) {
        this.discusscontenttype = discusscontenttype == null ? null : discusscontenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.PraiseCount
     *
     * @return the value of tb_topicforumprocess.PraiseCount
     *
     * @mbg.generated
     */
    public Integer getPraisecount() {
        return praisecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.PraiseCount
     *
     * @param praisecount the value for tb_topicforumprocess.PraiseCount
     *
     * @mbg.generated
     */
    public void setPraisecount(Integer praisecount) {
        this.praisecount = praisecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.ReferenceID
     *
     * @return the value of tb_topicforumprocess.ReferenceID
     *
     * @mbg.generated
     */
    public Integer getReferenceid() {
        return referenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.ReferenceID
     *
     * @param referenceid the value for tb_topicforumprocess.ReferenceID
     *
     * @mbg.generated
     */
    public void setReferenceid(Integer referenceid) {
        this.referenceid = referenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.ReferenceCount
     *
     * @return the value of tb_topicforumprocess.ReferenceCount
     *
     * @mbg.generated
     */
    public Integer getReferencecount() {
        return referencecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.ReferenceCount
     *
     * @param referencecount the value for tb_topicforumprocess.ReferenceCount
     *
     * @mbg.generated
     */
    public void setReferencecount(Integer referencecount) {
        this.referencecount = referencecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topicforumprocess.DiscussTime
     *
     * @return the value of tb_topicforumprocess.DiscussTime
     *
     * @mbg.generated
     */
    public Date getDiscusstime() {
        return discusstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topicforumprocess.DiscussTime
     *
     * @param discusstime the value for tb_topicforumprocess.DiscussTime
     *
     * @mbg.generated
     */
    public void setDiscusstime(Date discusstime) {
        this.discusstime = discusstime;
    }
}